feature/nagao task 1
connec10/training_vue pull request #7
Opened 2022-05-31 06:54 UTC by c-hikaru-nagao

**概要**
Training_vue1(Vue.jsの基本)の課題を実装。

**対応内容**
画面設計を基に、以下内容を実装。

課題1
・menusオブジェクトのデータをv-forを使用して表示。

課題2
・注文数に変更があった時、menusのquantityが変更されるようv-modelを使用して双方向データバインディングを使用して実装。
・menu.quantityが1以上になった場合、寿司ネタ x ◯皿となるよう算出プロパティにquantityが0以上だった場合、ハッシュを追加していく処理を追加。
また、その配列を、v-forを使用して表示。

課題3
・注文するのbuttonタグがclickされると、空配列(orderHistories)にハッシュが挿入されるmethodを作成。
・注文履歴の下にv-forを使用してorderHistoriesを表示。

課題4
・orderHistoriedのpriceを基準に、小計、税、合計が表示されるよう、computedに処理を追加。

課題5
・デフォルト値が、文字列menusのnavStatusデータオプションを用意。
・メニュー注文が押下されたときは、navStatusがmenus。
　注文履歴が押下されたときは、navStatusがbasketとなるmethodを追加。

・-showを使用して、navStatusがmenusかbasketなのかで、表示が変更されるDomが変更されるよう設定。

2022-05-31 06:59 UTC, c-hikaru-nagao commented on training_vue/public/task_vue_basic.html
> +        id: 1,
v-for時に、v-bind:keyで一意の値を設定する必要があるため、処理を追加。

2022-06-05 15:44 UTC, youhei-tsutsumi requested changes

2022-06-05 15:44 UTC, youhei-tsutsumi commented on training_vue/public/task_vue_basic.html
> +          <li>{{order | formatOrderName }}</li>
半角スペース空けましょう。
```suggestion
          <li>{{ order | formatOrderName }}</li>
```

2022-06-05 15:44 UTC, youhei-tsutsumi commented on training_vue/public/task_vue_basic.html
> +          <li>税：{{ orderTax | formatPrice}}円</li>
```suggestion
          <li>税：{{ orderTax | formatPrice }}円</li>
```

2022-06-05 15:44 UTC, youhei-tsutsumi commented on training_vue/public/task_vue_basic.html
> +      }
filter使うともっと楽にかけると思います。

2022-06-05 15:44 UTC, youhei-tsutsumi commented on training_vue/public/task_vue_basic.html
> +        if (list.quantity > 0) {
orderListsですでに、quantity > 0 以上のものをもってきているのに
ここで更に条件分岐するのは何か意図ありますか？

2022-06-05 15:44 UTC, youhei-tsutsumi commented on training_vue/public/task_vue_basic.html
> +          menu.quantity = 0
これ、orderListsの繰り返しのところでやってもいいかも。

2022-06-05 15:44 UTC, youhei-tsutsumi commented on training_vue/public/task_vue_basic.html
> +      for (let list of this.orderLists) {
listが複数形のものに見えてしまうので、変数名変えたほうがいいですね。
orderMenuとか。

2022-12-19 01:52 UTC, c-hikaru-nagao commented on training_vue/public/task_vue_basic.html
> +          <li>{{order | formatOrderName }}</li>
失礼しました。
半角スペースの修正いたしました。

2022-12-19 01:52 UTC, c-hikaru-nagao commented on training_vue/public/task_vue_basic.html
> +      }
ご指摘いただきありがとうございます。

こちらはfilter()を使用して修正しました。

2022-12-19 01:52 UTC, c-hikaru-nagao commented on training_vue/public/task_vue_basic.html
> +        if (list.quantity > 0) {
失礼しました。
こちらは無駄な判定となっていた為、修正いたしました。

2022-12-19 01:54 UTC, c-hikaru-nagao commented on training_vue/public/task_vue_basic.html
> +          menu.quantity = 0
ご指摘いただきありがとうございます。

こちらはorderListsのループ内に処理を記載いたしました。

2022-12-19 01:54 UTC, c-hikaru-nagao commented on training_vue/public/task_vue_basic.html
> +      for (let list of this.orderLists) {
こちらはorderMenuとして変数名修正いたしました。

2022-12-19 01:56 UTC, c-hikaru-nagao commented on training_vue/public/task_vue_basic.html
> +        <button :disabled="canAddOrder" @click="addOrder">注文する</button>
注文リストがない状態でも、ボタンが押下できておりました。

その為、課題にはないですが、注文リストがない場合、ボタンを非活性にするようにしました。

2022-12-27 07:21 UTC, youhei-tsutsumi approved these changes
Approve！！

2022-12-27 07:21 UTC, merged